services:
  app:
    build: .
    container_name: api
    ports:
      - "8007:8007"
    environment:
      APP_ENV: production
    restart: unless-stopped
#    depends_on:
#      - db

#  db:
#    image: postgres:16
#    restart: always
#    volumes:
#      - db_data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER:-postgres}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
#      POSTGRES_DB: db
#      PGDATABASE: db
#      PGPASSWORD: ${POSTGRES_PASSWORD:-passwd}
#      PG_USER: ${POSTGRES_USER:-postgres}
#    ports:
#      - 127.0.0.1:${LOCAL_DB_PORT:-54321}:5432
#
#volumes:
#  db_data:
